controllerManager:
  # Restrict the operator to watch a specific target namespace (e.g. run in namespace X, watch namespace Y).
  watchNamespace: ""
  # Restrict the operator to watch only the namespace it is deployed in (run in X, watch X).
  watchCurrentNamespace: false
  # Allow webhooks to be created and grant cluster-wide validatingwebhookconfiguration permissions even in gapped mode.
  enableWebhooksInGappedMode: false
  manager:
    args:
    - --metrics-bind-address=:8443
    - --leader-elect
    - --health-probe-bind-address=:8081
    - --zap-log-level=debug
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
    image:
      repository: example.com/typesense-operator
      tag: v0.0.1
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 10m
        memory: 64Mi
  nodeSelector: {}
  podSecurityContext:
    runAsNonRoot: true
  replicas: 1
  tolerations: []
  topologySpreadConstraints: []
kubernetesClusterDomain: cluster.local
metricsService:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  type: ClusterIP
serviceAccount:
  annotations: {}
  automount: true
  create: true
  name: ""
webhookService:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  type: ClusterIP
imagePullSecrets: []
