apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "typesense-operator.fullname" . }}-controller-manager
  labels:
    control-plane: controller-manager
  {{- include "typesense-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controllerManager.replicas }}
  selector:
    matchLabels:
      control-plane: controller-manager
    {{- include "typesense-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        control-plane: controller-manager
      {{- include "typesense-operator.selectorLabels" . | nindent 8 }}
      annotations:
        kubectl.kubernetes.io/default-container: manager
    spec:
      containers:
      - args:
{{- range .Values.controllerManager.manager.args }}
        - {{ . | quote }}
{{- end }}
{{- if .Values.controllerManager.watchNamespace }}
        - --watch-namespace={{ .Values.controllerManager.watchNamespace }}
{{- end }}
{{- if .Values.controllerManager.watchCurrentNamespace }}
        - --watch-current-namespace
{{- end }}
{{- if and (or .Values.controllerManager.watchNamespace .Values.controllerManager.watchCurrentNamespace) (not .Values.controllerManager.enableWebhooksInGappedMode) }}
        - --enable-webhook=false
{{- end }}
        command:
        - /manager
        env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: WEBHOOK_SERVICE_NAME
          value: {{ include "typesense-operator.fullname" . }}-webhook-service
{{- if .Values.controllerManager.watchNamespace }}
        - name: WATCH_NAMESPACE
          value: {{ .Values.controllerManager.watchNamespace | quote }}
{{- end }}
{{- if .Values.controllerManager.watchCurrentNamespace }}
        - name: WATCH_CURRENT_NAMESPACE
          value: "true"
{{- end }}
        image: {{ .Values.controllerManager.manager.image.repository }}:{{ .Values.controllerManager.manager.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.controllerManager.manager.imagePullPolicy }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources: {{- toYaml .Values.controllerManager.manager.resources | nindent 10
          }}
        securityContext: {{- toYaml .Values.controllerManager.manager.containerSecurityContext
          | nindent 10 }}
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: webhook-certs
      nodeSelector: {{- toYaml .Values.controllerManager.nodeSelector | nindent 8 }}
      securityContext: {{- toYaml .Values.controllerManager.podSecurityContext | nindent
        8 }}
      imagePullSecrets: {{ .Values.imagePullSecrets | default list | toJson }}
      serviceAccountName: {{ include "typesense-operator.serviceAccountName" . }}
      terminationGracePeriodSeconds: 10
      tolerations: {{- toYaml .Values.controllerManager.tolerations | nindent 8 }}
      topologySpreadConstraints: {{- toYaml .Values.controllerManager.topologySpreadConstraints
        | nindent 8 }}
      volumes:
      - emptyDir: {}
        name: webhook-certs
