apiVersion: rbac.authorization.k8s.io/v1
{{ $isNamespaced := or .Values.controllerManager.watchNamespace .Values.controllerManager.watchCurrentNamespace -}}
{{ $targetNamespace := .Values.controllerManager.watchNamespace | default .Release.Namespace -}}
kind: {{ if $isNamespaced }}Role{{ else }}ClusterRole{{ end }}
metadata:
  name: {{ include "typesense-operator.fullname" . }}-manager-role
  {{- if $isNamespaced }}
  namespace: {{ $targetNamespace }}
  {{- end }}
  labels:
  {{- include "typesense-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumeclaims
  - pods
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - get
  - patch
  - update
{{- if not $isNamespaced }}
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  verbs:
  - get
  - list
  - patch
  - update
  - watch
{{- end }}
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - httproutes
  - referencegrants
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - podmonitors
  - servicemonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses/finalizers
  verbs:
  - update
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ts.opentelekomcloud.com
  resources:
  - typesenseclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ts.opentelekomcloud.com
  resources:
  - typesenseclusters/finalizers
  verbs:
  - update
- apiGroups:
  - ts.opentelekomcloud.com
  resources:
  - typesenseclusters/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ if $isNamespaced }}RoleBinding{{ else }}ClusterRoleBinding{{ end }}
metadata:
  name: {{ include "typesense-operator.fullname" . }}-manager-rolebinding
  {{- if $isNamespaced }}
  namespace: {{ $targetNamespace }}
  {{- end }}
  labels:
  {{- include "typesense-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ if $isNamespaced }}Role{{ else }}ClusterRole{{ end }}
  name: '{{ include "typesense-operator.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "typesense-operator.serviceAccountName" . }}'
  namespace: '{{ .Release.Namespace }}'
{{- if and $isNamespaced .Values.controllerManager.enableWebhooksInGappedMode }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "typesense-operator.fullname" . }}-webhook-role
  labels:
  {{- include "typesense-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  verbs:
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "typesense-operator.fullname" . }}-webhook-rolebinding
  labels:
  {{- include "typesense-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "typesense-operator.fullname" . }}-webhook-role
subjects:
- kind: ServiceAccount
  name: {{ include "typesense-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
