apiVersion: rbac.authorization.k8s.io/v1
{{ $isNamespaced := or .Values.controllerManager.watchNamespace .Values.controllerManager.watchCurrentNamespace -}}
{{ $targetNamespace := .Values.controllerManager.watchNamespace | default .Release.Namespace -}}
kind: {{ if $isNamespaced }}Role{{ else }}ClusterRole{{ end }}
metadata:
  name: {{ include "typesense-operator.fullname" . }}-typesensecluster-viewer-role
  {{- if $isNamespaced }}
  namespace: {{ $targetNamespace }}
  {{- end }}
  labels:
  {{- include "typesense-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ts.opentelekomcloud.com
  resources:
  - typesenseclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ts.opentelekomcloud.com
  resources:
  - typesenseclusters/status
  verbs:
  - get
