{{- $isNamespaced := or .Values.controllerManager.watchNamespace .Values.controllerManager.watchCurrentNamespace -}}
{{- if or (not $isNamespaced) .Values.controllerManager.enableWebhooksInGappedMode }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "typesense-operator.fullname" . }}-validating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "typesense-operator.fullname" . }}-
  labels:
  {{- include "typesense-operator.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "typesense-operator.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /validate-ts-opentelekomcloud-com-v1alpha1-typesensecluster
  failurePolicy: Fail
  name: vtypesensecluster.kb.io
  rules:
  - apiGroups:
    - ts.opentelekomcloud.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - typesenseclusters
  sideEffects: None
{{- end }}
